# Generated by Django 3.2.8 on 2022-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='Phone Number'),
        ),
    ]
