# Generated by Django 3.2.8 on 2022-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='cin_pic_back',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='PicBackImage'),
        ),
        migrations.AddField(
            model_name='producer',
            name='cin_pic_front',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='PicFrontImage'),
        ),
        migrations.AddField(
            model_name='producer',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='image'),
        ),
    ]
