# Generated by Django 3.2.8 on 2022-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_auto_20220215_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.FileField(blank=True, default=None, max_length=100000, null=True, upload_to='', verbose_name='image'),
        ),
    ]
