# Generated by Django 3.2.8 on 2022-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_alter_producer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='cin_pic_back',
            field=models.FileField(blank=True, default=None, max_length=100000, null=True, upload_to='', verbose_name='cin_pic_back'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='cin_pic_front',
            field=models.FileField(blank=True, default=None, max_length=100000, null=True, upload_to='', verbose_name='cin_pic_front'),
        ),
    ]
