# Generated by Django 3.2.8 on 2022-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20220224_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Age'),
        ),
    ]
