# Generated by Django 3.2.8 on 2022-03-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('producer', '0005_alter_producer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BinBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone_one', models.CharField(max_length=100)),
                ('phone_two', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='geo.address')),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='50x20x10', max_length=50)),
                ('volume', models.FloatField(default='0')),
                ('color', models.CharField(max_length=100)),
                ('bar_code', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producer.binbrand')),
                ('type_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producer.bintype')),
            ],
        ),
    ]
