# Generated by Django 3.2.8 on 2022-03-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_bin_binbrand_bintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='bar_code',
        ),
        migrations.AddField(
            model_name='bin',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Producer'),
        ),
    ]
