# Generated by Django 3.2.8 on 2022-03-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0007_auto_20220316_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binbrand',
            name='address',
        ),
    ]
