# Generated by Django 3.2.8 on 2022-03-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('producer', '0010_alter_bin_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producer.binbrand'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='type_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producer.bintype'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='volume',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_barn',
            field=models.BooleanField(default=False, null=True, verbose_name='Barn'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(default=False, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False, null=True, verbose_name='Garden'),
        ),
    ]
