# Generated by Django 3.2.8 on 2022-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0011_auto_20220324_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bintype',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bintype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
