# Generated by Django 3.2.8 on 2022-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0012_auto_20220324_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='type_bin',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='property',
            name='individuals',
            field=models.IntegerField(default=0, null=True, verbose_name='Individuals'),
        ),
    ]
