# Generated by Django 3.2.8 on 2021-12-14 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='Country Code')),
                ('name', models.CharField(max_length=256, verbose_name='Country Name')),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Shape')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Municipality Name')),
                ('name_ar', models.CharField(max_length=256, verbose_name='Municipality Name')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Municipality Code')),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Shape')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='State Code')),
                ('name', models.CharField(max_length=256, verbose_name='State Name')),
                ('name_ar', models.CharField(max_length=256, verbose_name='State Arabic Name')),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Shape')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='District Code')),
                ('name', models.CharField(max_length=256, verbose_name='District Name')),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Shape')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lines')),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Zip Code')),
                ('is_spatial', models.BooleanField(default=False, verbose_name='Spatial')),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326, verbose_name='Localisation')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.district', verbose_name='District')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.municipality', verbose_name='Municipality')),
            ],
        ),
    ]
