# Generated by Django 3.2.8 on 2021-12-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=256, verbose_name='Legal Name')),
                ('registration', models.CharField(blank=True, max_length=256, null=True, verbose_name='Registre Number')),
                ('code_tva', models.CharField(blank=True, max_length=256, null=True, verbose_name='TVA Code')),
                ('creation_date', models.DateField(blank=True, default=None, null=True, verbose_name='Creation Date')),
                ('phone_number_one', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Phone 1')),
                ('phone_number_two', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Phone 2')),
                ('fax', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Fax')),
                ('email', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Website')),
                ('contact', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Contact Name')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('is_municipality', models.BooleanField(default=False, verbose_name='Municipality')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('municipality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.municipality')),
            ],
        ),
    ]
