# Generated by Django 3.2.6 on 2021-10-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='label')),
                ('street', models.CharField(max_length=100, verbose_name='Rue')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('state', models.CharField(max_length=100, verbose_name='Etat')),
                ('country', models.CharField(max_length=50, verbose_name='Pays')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('is_spatial', models.BooleanField(default=False, verbose_name='Spatial')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(default=0.0, null=True, verbose_name='Area')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Jardin')),
                ('has_garage', models.BooleanField(default=False, verbose_name='Garage')),
                ('is_residence', models.BooleanField(default=True, verbose_name='Résident')),
                ('is_commercial', models.BooleanField(default=False, verbose_name='Commerce')),
                ('is_public', models.BooleanField(default=False, verbose_name='Publié')),
                ('individuals', models.IntegerField(default=0, max_length=100000, verbose_name='Individus')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producers.address')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producers.propertytype')),
            ],
        ),
    ]
