# Generated by Django 3.2.6 on 2021-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='individuals',
            field=models.IntegerField(default=0, verbose_name='Individus'),
        ),
    ]
